[project]
name = "xai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kdjoumessi", email = "djoumessikerol@gmail.com" }
]
requires-python = ">=3.12,<3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.3",
    "pandas>=3.0.5",
    "pillow>=12.3.0",
]

[project.scripts]
xai = "xai:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
explicit = true